### ISSUE TITLE
Can't access from webstore

### ISSUE THREAD

**Issue by TheClaus** [gabrielbarros/floating-player#16]
I was going to write you about an issue I was seeing and found that this extension isn't on the webstore.  Please tell me you aren't giving up on this wonderful extension.  I love it so much and would hate to see such a lite app like this go away

**Comment by gabrielbarros** [comment]
Nah... Google has disabled it because they said the extension name was too long. :cry:

I just uploaded a new version. It may take a few days to return to Chrome Web Store.

See my e-mails:

-------------------------------------

**Action Required: Floating Player: YouTube, Twitch.tv, etc. Requires Changes to Comply with Chrome Web Store Policy**

Dear Developer,

We routinely review items in the Chrome Web Store for compliance with our Program policies to ensure a safe and trusted experience for our users. We recently found that your item, "Floating Player: YouTube, Twitch.tv, etc.," with ID: ekajjllcmeckibblgckgoceinmmgnfop did not comply with our policies. Your item did not comply with the following section of our policy: Do not use irrelevant, misleading, or excessive keywords in app descriptions, titles, or metadata. Your item is still published, but is at risk of being removed from the Web Store.

Please make the above changes within 7 days in order to avoid removal: Once you have made these changes you may submit and publish a new draft in the developer dashboard. Your draft will be reviewed for policy compliance which typically takes a few business days. If the outcome of the review is successful, your store listing will remain published. If we find additional issues with your item, we will send you another email with details. If you have any questions about this email, please respond and the Chrome Web Store developer support team will follow up with you.

Important Note:

Your item will still be subject to review and may be removed from the store within the warning period. Repeated or egregious policy violations in the Chrome Web Store may result in your developer account being suspended or could lead to a ban from using the Chrome Web Store platform. This may also result in the suspension of related Google services associated with your Google account.

Thank you for your cooperation,

Google Chrome Web Store team

\---------------------------

Developer Terms of Service: https://developers.google.com/chrome/web-store/terms

Program Policies: https://developers.google.com/chrome/web-store/program_policies

Branding Guidelines: https://developers.google.com/chrome/web-store/branding

---------------------------

**Chrome Web Store: Removal notification for Floating Player: YouTube, Twitch.tv, etc.**


Dear Developer,

Your Google Chrome item, "Floating Player: YouTube, Twitch.tv, etc.," with ID: ekajjllcmeckibblgckgoceinmmgnfop did not comply with our policies and was removed from the Google Chrome Web Store.

Your item did not comply with the following section of our policy:

"Do not post repetitive content.
Do not use irrelevant, misleading, or excessive keywords in app descriptions, titles, or metadata.
Do not attempt to change the placement of any Product in the store or manipulate any Product ratings or reviews by unauthorized means, such as fraudulent installs, paid or fake reviews or ratings, or offering incentives to rate Products.
Do not post an app where the primary functionality is to link to a website not owned by the developer.
Do not post an app where the primary functionality is to install or launch another app, theme, or extension. For example, if your app’s primary function is to launch a desktop app that the user has already installed, that is not allowed. Another example is a packaged app that just launches a website.
Your app must comply with Google's Webmaster Quality Guidelines."

If you'd like to re-submit your item, please make the appropriate changes to the item so that it complies with our policies, then re-publish it in your developer dashboard. Please reply to this email for issues regarding this item removal.

*Please keep in mind that your re-submitted item will not be immediately published live in the store. All re-submitted items undergo a strict compliance review and will be re-published if the item passes review.

*Important Note
Repeated or egregious violations in the store may result in your developer account being banned from the store. This may also result in the suspension of related Google services associated with your Google account. All re-submitted items will continue to be subject to Chrome Web Store policies and terms of service.

Thank you for your cooperation,
Google Chrome Web Store team

\---------------------------
Developer Terms of Service:
https://developers.google.com/chrome/web-store/terms

Program Policies:
https://developers.google.com/chrome/web-store/program_policies

Branding Guidelines:
https://developers.google.com/chrome/web-store/branding

**Comment by TheClaus** [comment]
Awesome I will create a new issue for what I am experiencing.

**Comment by gabrielbarros** [comment]
I'll keep this open for now, ok?
