### ISSUE TITLE
Window resizing

### ISSUE THREAD

**Issue by tfaehnle** [gabrielbarros/floating-player#7]
This would be a feature request.

Current behavior: when the floating player is already open, I pop another video out into the floating player the window resizes and moves.

Desired behavior: an option in the settings not to resize and move (one for each resize and move, probably) whereby popping out another video in the floating player reuses the window without moving or resizing it.

I regularly change the size and position of the window while I'm doing my work throughout the day depending on the video and what else I'm trying to get done, and I don't want to have to resize the video every time the previous one ends (and I often switch between twitch and youtube, so playlists aren't really feasible)

**Comment by gabrielbarros** [comment]
I see. I'm going to create an option called "Keep position and current dimensions of popup when changing video".

If it's checked, the window won't be resized or moved under any circumstances.

Is it ok for you?

--------

*PS.: You can also uncheck the option "Open YouTube video with the correct aspect ratio", so that the window stays in 16:9 when the first video is played*

**Comment by tfaehnle** [comment]
That would be perfect!

**Comment by gabrielbarros** [comment]
Done. (v2.0.33)

Go to chrome://extensions, check "Developer mode" and click "Update extensions now".
